apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: searcher
  description: Searcher
  annotations:
    dev.azure.com/project-repo: GDPS/GDPS_Config
  tags:
    - go
spec:
  type: service
  lifecycle: production
  owner: user:guest
